services:

  mvideo_parser:
    build:
      context: .
    command: python parser/app.py

  telegram_messages:
    build:
      context: .
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command: python parser/telegram_messages.py
